dbt_notion:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: onboarding_agent
      threads: 4
      timeout_seconds: 300
      location: asia-northeast3
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: onboarding_agent
      threads: 4
      timeout_seconds: 300
      location: asia-northeast3
